# Generated by Django 5.2 on 2025-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktool', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='stock_symbol',
            field=models.CharField(max_length=20),
        ),
    ]
